version: '3'

services:
  nginx:
    image: nginx:1-alpine
    container_name: ${APP_NAME}-php-nginx
    ports:
      - 8080:80
    links:
      - app
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

  app:
    image: ${APP_NAME}/app
    build:
      context: ./docker/app
      args:
        UID: ${APP_UID}
    container_name: ${APP_NAME}-php-app
    volumes:
      - ~/.ssh:/home/dev/.ssh # share SSH keys with container
      - ./:/var/www
    links:
      - db

  db:
    image: postgres:13-alpine
    container_name: ${APP_NAME}-php-db
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
    ports:
      - 31000-31999:5432
